[env]
_.path = ["~/.local/share/bob/nvim-bin"]

[tools]
bob = "latest"
ripgrep = "latest"
tree-sitter = "latest"
'npm:@zed-industries/vscode-langservers-extracted' = 'latest'
'npm:eslint_d' = 'latest'
'npm:prettier' = 'latest'
"npm:@typescript/native-preview" = "latest"
lua-language-server = "latest"
stylua = 'latest'
'cargo:selene' = 'latest'
'npm:@olrtg/emmet-language-server' = 'latest'
'npm:@tailwindcss/language-server' = 'latest'
'npm:@astrojs/language-server' = 'latest'
'npm:unocss-language-server' = 'latest'
taplo = 'latest'
'pipx:basedpyright' = 'latest'
ruff = 'latest'
zig = "latest"
zls = "latest"
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:github.com/a-h/templ/cmd/templ" = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"go:github.com/docker/docker-language-server/cmd/docker-language-server" = "latest"
"golangci-lint" = "latest"
"golangci-lint-langserver" = "latest"
shfmt = "latest"
shellcheck = "latest"
"npm:bash-language-server" = "latest"
"cargo:kdlfmt" = "latest"
"cargo:kdl-lsp" = "latest"
tinymist = "latest"
typst = "latest"

[settings.npm]
bun = true
